---
- name: Hello Acme
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show it works
      debug:
        msg: 'This is ACME, Inc content {{ ee_registry_username | default("Test") }} - {{ ee_registry_password | default("") }}'
